-- Movimientos de caja: cada venta o gasto que se carga desde la pantalla
-- "Cargar" de app.html. Es la tabla principal de la app.
--
-- NOTA: esto ya está aplicado en la base real de Tikera. Este archivo
-- documenta el esquema completo para que el repo sea reproducible desde
-- cero -- no hace falta volver a correrlo salvo que estés levantando un
-- proyecto de Supabase nuevo.

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null,
  hora text,
  tipo text not null, -- 'Venta' | 'Gasto'
  descripcion text not null,
  cantidad numeric,
  precio_unitario numeric,
  costo_unitario numeric,
  costo_total numeric,
  ganancia numeric,
  monto numeric not null,
  metodo_pago text,
  nota text,
  created_at timestamptz not null default now()
);

alter table public.movements enable row level security;

create policy "movements_select_own" on public.movements
  for select using (auth.uid() = user_id);

create policy "movements_insert_own" on public.movements
  for insert with check (auth.uid() = user_id);

create policy "movements_update_own" on public.movements
  for update using (auth.uid() = user_id);

create policy "movements_delete_own" on public.movements
  for delete using (auth.uid() = user_id);

create index if not exists movements_user_id_idx on public.movements(user_id);
create index if not exists movements_fecha_idx on public.movements(fecha);
