-- Productos y gastos frecuentes: los chips de acceso rápido en la pantalla
-- "Cargar" ("Agregar producto frecuente"), separados por tipo (Venta/Gasto).
--
-- NOTA: esto ya está aplicado en la base real de Tikera (RLS incluido,
-- verificado con `select relrowsecurity from pg_class where relname =
-- 'frequent_items';` -> true). Se documenta acá para que el repo refleje
-- el esquema completo real.

create table if not exists public.frequent_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null, -- 'Venta' | 'Gasto'
  nombre text not null,
  created_at timestamptz not null default now()
);

alter table public.frequent_items enable row level security;

create policy "frequent_items_select_own" on public.frequent_items
  for select using (auth.uid() = user_id);

create policy "frequent_items_insert_own" on public.frequent_items
  for insert with check (auth.uid() = user_id);

create policy "frequent_items_delete_own" on public.frequent_items
  for delete using (auth.uid() = user_id);

create index if not exists frequent_items_user_id_idx on public.frequent_items(user_id);
