-- Proveedores: a quién le comprás mercadería y qué le debés.
-- Correr una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nombre text not null,
  contacto text,
  notas text,
  created_at timestamptz not null default now()
);

alter table public.proveedores enable row level security;

create policy "proveedores_select_own" on public.proveedores
  for select using (auth.uid() = user_id);

create policy "proveedores_insert_own" on public.proveedores
  for insert with check (auth.uid() = user_id);

create policy "proveedores_update_own" on public.proveedores
  for update using (auth.uid() = user_id);

create policy "proveedores_delete_own" on public.proveedores
  for delete using (auth.uid() = user_id);

create index if not exists proveedores_user_id_idx on public.proveedores(user_id);

-- Cada entrega/pedido de un proveedor: qué trajo, cuánto hay que pagarle,
-- y si ya se le pagó o todavía está pendiente.
create table if not exists public.pedidos_proveedor (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  proveedor_id bigint not null references public.proveedores(id) on delete cascade,
  fecha date not null,
  descripcion text not null,
  cantidad numeric,
  monto numeric not null,
  pagado boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.pedidos_proveedor enable row level security;

create policy "pedidos_proveedor_select_own" on public.pedidos_proveedor
  for select using (auth.uid() = user_id);

-- Además de user_id, el proveedor_id tiene que ser un proveedor propio: la FK
-- sola no lo garantiza, y sin esto alguien podría colgar pedidos de un
-- proveedor ajeno (y se borrarían en cascada cuando el otro lo elimine).
create policy "pedidos_proveedor_insert_own" on public.pedidos_proveedor
  for insert with check (
    auth.uid() = user_id
    and exists (select 1 from public.proveedores p where p.id = proveedor_id and p.user_id = auth.uid())
  );

create policy "pedidos_proveedor_update_own" on public.pedidos_proveedor
  for update using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.proveedores p where p.id = proveedor_id and p.user_id = auth.uid())
  );

create policy "pedidos_proveedor_delete_own" on public.pedidos_proveedor
  for delete using (auth.uid() = user_id);

create index if not exists pedidos_proveedor_user_id_idx on public.pedidos_proveedor(user_id);
create index if not exists pedidos_proveedor_proveedor_id_idx on public.pedidos_proveedor(proveedor_id);
