-- Cierre de caja: cuanto efectivo esperaba tener segun lo cargado en el dia
-- (ventas menos gastos en efectivo) contra lo que el kiosquero cuenta a mano.
-- Correr una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.cierres_caja (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null,
  efectivo_esperado numeric not null,
  efectivo_contado numeric not null,
  diferencia numeric not null,
  notas text,
  created_at timestamptz not null default now()
);

alter table public.cierres_caja enable row level security;

create policy "cierres_caja_select_own" on public.cierres_caja
  for select using (auth.uid() = user_id);

create policy "cierres_caja_insert_own" on public.cierres_caja
  for insert with check (auth.uid() = user_id);

create policy "cierres_caja_update_own" on public.cierres_caja
  for update using (auth.uid() = user_id);

create policy "cierres_caja_delete_own" on public.cierres_caja
  for delete using (auth.uid() = user_id);

create index if not exists cierres_caja_user_id_idx on public.cierres_caja(user_id);
create index if not exists cierres_caja_fecha_idx on public.cierres_caja(fecha);
