-- Historial de conversacion con el asistente de IA: cada mensaje (del
-- usuario y del agente) queda guardado para que la conversacion tenga
-- memoria y para poder contar cuantas consultas hizo hoy (limite diario).
-- Correr una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.agent_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.agent_messages enable row level security;

create policy "agent_messages_select_own" on public.agent_messages
  for select using (auth.uid() = user_id);

create policy "agent_messages_insert_own" on public.agent_messages
  for insert with check (auth.uid() = user_id);

create policy "agent_messages_delete_own" on public.agent_messages
  for delete using (auth.uid() = user_id);

create index if not exists agent_messages_user_id_idx on public.agent_messages(user_id);
create index if not exists agent_messages_created_at_idx on public.agent_messages(created_at);
