-- Facturacion electronica (ARCA, ex-AFIP): cada kiosco factura bajo su
-- propio CUIT, Tikera no puede "prenderlo" centralizado para todos. Esto
-- guarda, por negocio, los datos para conectarse a los servicios de ARCA
-- (facturacion_config) y el resultado de pedir un CAE por cada venta
-- facturada (facturas).
-- Correr una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.facturacion_config (
  user_id uuid primary key references auth.users(id) on delete cascade,
  cuit text,
  razon_social text,
  punto_venta integer,
  tipo_comprobante_default text not null default 'C' check (tipo_comprobante_default in ('A','B','C')),
  ambiente text not null default 'homologacion' check (ambiente in ('homologacion','produccion')),
  -- Certificado y clave privada cifrados (AES-GCM) por la Edge Function antes
  -- de guardarlos -- nunca viajan ni se guardan en texto plano. La clave de
  -- cifrado vive solo como secret de la funcion (ARCA_CERT_ENC_KEY), jamas
  -- en esta base.
  certificado_enc text,
  clave_privada_enc text,
  activado boolean not null default false,
  verificado_at timestamptz,
  -- Ticket de WSAA (login contra ARCA) cacheado: dura ~12hs y ARCA rechaza
  -- un login nuevo si todavia hay uno vigente, asi que hay que reusarlo.
  wsaa_token text,
  wsaa_sign text,
  wsaa_expira timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.facturas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Una sola factura por venta: ademas de logica de negocio, es el backstop
  -- real contra doble click o dos pestañas pidiendo dos CAE para la misma venta.
  movement_id bigint not null references public.movements(id) on delete cascade unique,
  tipo_comprobante text not null,
  punto_venta integer not null,
  numero bigint,
  cae text,
  cae_vencimiento date,
  estado text not null default 'pendiente' check (estado in ('pendiente','emitida','error')),
  fecha_emision timestamptz,
  ambiente text not null,
  error_mensaje text,
  -- Snapshot del importe en el momento de facturar: el CAE queda atado al
  -- monto que se le declaro a ARCA, no al valor actual de la venta si se
  -- edita despues.
  monto numeric not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.facturacion_config enable row level security;
alter table public.facturas enable row level security;

create policy "facturacion_config_select_own" on public.facturacion_config
  for select using (auth.uid() = user_id);

create policy "facturas_select_own" on public.facturas
  for select using (auth.uid() = user_id);

-- Sin policies de insert/update/delete para ninguna de las dos tablas: toda
-- escritura pasa por las Edge Functions (arca-config, arca-facturar) con
-- service role. No alcanza con RLS comun aca -- un cliente autenticado-como-
-- el-usuario (como usa ai-agent) es indistinguible a nivel de Postgres del
-- propio navegador, asi que no hay forma de decir "esto lo escribe la
-- funcion, no el usuario directo" sin service role. Mismo motivo estructural
-- por el que delete-account ya lo necesita.
--
-- Igual, por las dudas de que algun dia se agregue un insert/update directo
-- del cliente: revocar explicitamente todo permiso de escritura de la tabla
-- completa, para no depender solo de "no hay policy".
revoke insert, update, delete on public.facturacion_config from authenticated;
revoke insert, update, delete on public.facturas from authenticated;

-- Ademas, en facturacion_config ni siquiera la LECTURA es pareja: el
-- certificado, la clave privada y el ticket de WSAA no tienen que llegar
-- nunca al cliente, ni cifrados. No es "no editable" -- directamente no
-- existen para el navegador.
revoke select on public.facturacion_config from authenticated;
grant select (
  user_id, cuit, razon_social, punto_venta, tipo_comprobante_default,
  ambiente, activado, verificado_at, created_at, updated_at
) on public.facturacion_config to authenticated;

create index if not exists facturas_user_id_idx on public.facturas(user_id);
create index if not exists facturas_movement_id_idx on public.facturas(movement_id);
