-- Módulo "Equipos" (rubro celulares/electrónica): inventario por UNIDAD, no por
-- cantidad. Cada fila es un equipo puntual con su IMEI/serie, estado, costo,
-- precio y garantía — así se puede seguir unidad por unidad (disponible,
-- reservado, vendido, en reparación) y calcular el margen de cada una.
--
-- Aislamiento por cuenta con RLS, igual que movements/products: cada usuario
-- solo ve y toca SUS equipos. Se otorgan los permisos de tabla explícitos para
-- no depender de defaults.
--
-- Correr una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.equipos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  marca text,
  modelo text,
  capacidad text,          -- ej. "128 GB"
  color text,
  imei text,               -- IMEI o número de serie
  estado text not null default 'disponible'
    check (estado in ('disponible','reservado','vendido','reparacion')),
  costo numeric,           -- costo de compra de esa unidad
  precio numeric,          -- precio de venta
  accesorios text,         -- ej. "caja, cargador, funda"
  garantia_hasta date,     -- hasta cuándo tiene garantía
  cliente text,            -- a quién se reservó / vendió (opcional)
  notas text,
  vendido_at timestamptz,  -- cuándo se marcó como vendido
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.equipos enable row level security;

create policy "equipos_select_own" on public.equipos
  for select using (auth.uid() = user_id);
create policy "equipos_insert_own" on public.equipos
  for insert with check (auth.uid() = user_id);
create policy "equipos_update_own" on public.equipos
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "equipos_delete_own" on public.equipos
  for delete using (auth.uid() = user_id);

grant select, insert, update, delete on public.equipos to authenticated;

create index if not exists equipos_user_id_idx on public.equipos(user_id);
