-- Catálogo de productos con stock, para la vista "Catálogo" de app.html.
-- Correr esto una sola vez en el SQL Editor de Supabase (Dashboard > SQL Editor > New query).

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  nombre text not null,
  precio_venta numeric,
  costo_unitario numeric,
  stock_actual numeric not null default 0,
  stock_minimo numeric,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "products_select_own" on public.products
  for select using (auth.uid() = user_id);

create policy "products_insert_own" on public.products
  for insert with check (auth.uid() = user_id);

create policy "products_update_own" on public.products
  for update using (auth.uid() = user_id);

create policy "products_delete_own" on public.products
  for delete using (auth.uid() = user_id);

create index if not exists products_user_id_idx on public.products(user_id);
